### ISSUE TITLE
Debug the typescipt app with skaffold

### ISSUE THREAD

**Issue by aryanPatilhm2** [hiteshjoshi1/ts-node-starter#7]
Hi Hitesh, is it possible to debug this typescript app with Skaffold in VS code? If yes then can you share the launch.json? I tried this code but not able to debug it. always getting (Breakpoint ignored because generated code not found) error. Also where ts-node is used in the app? I saw the app build with tsc and run with node command.

Thanks...

**Comment by hiteshjoshi1** [comment]
Well couple of things - 
- I did this starter back when i was looking for a nodejs starter written in Typescript. That is why the name ts-node-starter (ts stands for typescript)  and has nothing to do with ts-node.
- The project is outdated and should be archived, lot of outdated things are in there, I am not a fan of tsoa and generation of routes.
- I feel that there are better ways to do nodejs apps with typescript right now. Have you looked at https://nestjs.com.
- skaffold debugging - I have not tried using breakpoints with skaffold,but I GUESS skaffold dev --inspect flag should work. The app auto reloads on changes. if you find out about debugging, please let me know.
